export declare class DtoTransactions {
    id: number;
    typeOperation: 'DEBIT' | 'CREDIT';
    sousServicesId: number;
    phonesId: number | null;
    partenerComptesId: number;
    partenersId: number;
    solde: number;
    commissionAmount: number;
    feeAmount: number;
    createdAt: Date;
    updatedAt: Date | null;
    state: 'ACTIVED' | 'INACTIVED' | 'DELETED';
    statut: 'SUCCESS' | 'PENDING' | 'PROCESSING' | 'FAILLED' | 'CANCELED';
    dateCreation: Date;
    dateSuccess: Date | null;
    dateCanceled: Date | null;
    dateProcessing: Date | null;
    dateFailled: Date | null;
    serviceName: string;
    message: string;
    errorMessage: string;
    sousServiceName: string;
    operateurName: string;
    telephoneNumberService: string | null;
    partnerCompteName: string;
    partenerName: string;
    commentaire: string | null;
    data: string | null;
    amount: number;
    urlIpn: string;
    phone: string;
    externalTransactionId: string;
    sousServiceTransactionId: string;
    dataSended: string;
    dataResponseCallback: string;
    callbackIsSend: number;
    transactionId: string;
    codeSousService: string;
}
